//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebBuscadorDirectores.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ListadoFiscalizados
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ListadoFiscalizados()
        {
            this.ListadoDirectores = new HashSet<ListadoDirectores>();
        }
    
        public long IdListadoFiscalizados { get; set; }
        public Nullable<System.DateTime> DateScraping { get; set; }
        public string Rut { get; set; }
        public string Entidad { get; set; }
        public string Estado { get; set; }
        public string UrlRegistroDirector { get; set; }
        public string UrlListadoEmisor { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ListadoDirectores> ListadoDirectores { get; set; }
    }
}
