//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebBuscadorDirectores.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ListadoDirectores
    {
        public long IdListadoDirectores { get; set; }
        public Nullable<long> IdListadoFiscalizados { get; set; }
        public Nullable<System.DateTime> DateScraping { get; set; }
        public string Rut { get; set; }
        public string Nombre { get; set; }
        public string Cargo { get; set; }
        public string FechaNombramiento { get; set; }
    
        public virtual ListadoFiscalizados ListadoFiscalizados { get; set; }
    }
}
