//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebBuscadorDirectores.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CmfChileEntities : DbContext
    {
        public CmfChileEntities()
            : base("name=CmfChileEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ListadoDirectores> ListadoDirectores { get; set; }
        public virtual DbSet<ListadoFiscalizados> ListadoFiscalizados { get; set; }
        public virtual DbSet<ListadoBusqueda> ListadoBusqueda { get; set; }
    }
}
